import { calculateExecutionScore, type FeatureModule } from './featureModule.ts';

function module(input: Omit<FeatureModule, 'priorityScore'>): FeatureModule {
  return { ...input, priorityScore: calculateExecutionScore(input.score) };
}

export const featureModules = [
  module({
    id: 'premium-valet',
    name: 'Premium Valet',
    stage: 'design',
    audience: ['parker-consumer', 'venue-partner'],
    route: '/modules/premium-valet',
    featureFlag: 'VITE_FEATURE_PREMIUM_VALET',
    appleReviewSafe: false,
    dataContract: { schemaName: 'PremiumValetRequest', version: 1, requiredFields: ['venueId', 'arrivalWindow', 'vehicleType'], optionalFields: ['addOns', 'tipCents'] },
    uiSurface: { route: '/valet', componentName: 'PremiumValetModule', appStoreExposure: 'hidden-behind-flag', consumerCopySafe: true },
    paymentFlow: 'stripe',
    complianceRisk: 'medium',
    score: { phiMarket: 9, phiExecution: 6, deltaDifferentiation: 8, feasibility: 7, lambdaSimilarity: 0.8 },
    constraints: { appStoreRisk: 4, engineeringEffort: 4, complianceRisk: 'medium', revenuePotential: 5, timeToReleaseWeeks: 4 },
    summary: 'High-revenue arrival service for nightlife and hospitality use cases; hidden from the current Parker-only build.',
    dependencies: ['payments', 'location', 'availability'],
  }),
  module({
    id: 'cottage-hospitality',
    name: 'Cottage Hospitality',
    stage: 'idea',
    audience: ['parker-consumer', 'provider-operator'],
    route: '/modules/cottage-hospitality',
    featureFlag: 'VITE_FEATURE_COTTAGE_HOSPITALITY',
    appleReviewSafe: false,
    dataContract: { schemaName: 'CottageServiceRequest', version: 1, requiredFields: ['serviceType', 'serviceArea', 'requestedAt'], optionalFields: ['partySize', 'dietaryNotes'] },
    uiSurface: { route: '/services/cottage', componentName: 'CottageHospitalityModule', appStoreExposure: 'hidden-behind-flag', consumerCopySafe: true },
    paymentFlow: 'stripe',
    complianceRisk: 'high',
    score: { phiMarket: 7, phiExecution: 4, deltaDifferentiation: 8, feasibility: 5, lambdaSimilarity: 0.5 },
    constraints: { appStoreRisk: 4, engineeringEffort: 5, complianceRisk: 'high', revenuePotential: 4, timeToReleaseWeeks: 8 },
    summary: 'Private chefs and in-home hospitality module; requires compliance review before public exposure.',
    dependencies: ['provider-vetting', 'payments', 'service-areas'],
  }),
  module({
    id: 'events-nightlife',
    name: 'Event & Nightlife Reservations',
    stage: 'design',
    audience: ['parker-consumer', 'venue-partner'],
    route: '/modules/events-nightlife',
    featureFlag: 'VITE_FEATURE_EVENTS_NIGHTLIFE',
    appleReviewSafe: true,
    dataContract: { schemaName: 'EventReservation', version: 1, requiredFields: ['eventId', 'venueId', 'reservationTime'], optionalFields: ['partySize', 'ticketTier'] },
    uiSurface: { route: '/events', componentName: 'EventsNightlifeModule', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'stripe',
    complianceRisk: 'medium',
    score: { phiMarket: 8, phiExecution: 7, deltaDifferentiation: 7, feasibility: 7, lambdaSimilarity: 0.75 },
    constraints: { appStoreRisk: 3, engineeringEffort: 3, complianceRisk: 'medium', revenuePotential: 4, timeToReleaseWeeks: 3 },
    summary: 'Consumer-safe discovery and reservation extension for nightlife venues and shows.',
    dependencies: ['events-feed', 'venue-data', 'checkout'],
  }),
  module({
    id: 'loyalty-rewards',
    name: 'Loyalty & Rewards',
    stage: 'internal-beta',
    audience: ['parker-consumer', 'venue-partner'],
    route: '/modules/loyalty-rewards',
    featureFlag: 'VITE_FEATURE_LOYALTY_REWARDS',
    appleReviewSafe: true,
    dataContract: { schemaName: 'LoyaltyAccount', version: 1, requiredFields: ['userId', 'pointsBalance'], optionalFields: ['tier', 'activePerks'] },
    uiSurface: { route: '/rewards', componentName: 'LoyaltyRewardsModule', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'none',
    complianceRisk: 'low',
    score: { phiMarket: 7, phiExecution: 8, deltaDifferentiation: 5, feasibility: 8, lambdaSimilarity: 0.9 },
    constraints: { appStoreRisk: 2, engineeringEffort: 2, complianceRisk: 'low', revenuePotential: 3, timeToReleaseWeeks: 2 },
    summary: 'Low-risk retention layer that can reuse existing points and saved-spots primitives.',
    dependencies: ['gamification', 'saved-spots'],
  }),
  module({
    id: 'music-concerts',
    name: 'Music & Concert Experiences',
    stage: 'idea',
    audience: ['parker-consumer', 'artist-promoter', 'venue-partner'],
    route: '/modules/music-concerts',
    featureFlag: 'VITE_FEATURE_MUSIC_CONCERTS',
    appleReviewSafe: true,
    dataContract: { schemaName: 'MusicExperience', version: 1, requiredFields: ['showId', 'venueId', 'startsAt'], optionalFields: ['artistId', 'ticketUrl', 'vipAvailable'] },
    uiSurface: { route: '/shows', componentName: 'MusicConcertsModule', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'stripe',
    complianceRisk: 'medium',
    score: { phiMarket: 8, phiExecution: 5, deltaDifferentiation: 8, feasibility: 6, lambdaSimilarity: 0.65 },
    constraints: { appStoreRisk: 3, engineeringEffort: 4, complianceRisk: 'medium', revenuePotential: 4, timeToReleaseWeeks: 5 },
    summary: 'Show discovery, VIP packages, and venue/artist partnerships under a consumer-safe module.',
    dependencies: ['events-feed', 'artist-data', 'checkout'],
  }),
  module({
    id: 'ai-concierge',
    name: 'Advanced Search & AI Concierge',
    stage: 'frozen',
    audience: ['parker-consumer'],
    route: '/modules/ai-concierge',
    featureFlag: 'VITE_FEATURE_AI_CONCIERGE',
    appleReviewSafe: false,
    dataContract: { schemaName: 'ConciergeIntent', version: 1, requiredFields: ['query', 'locationContext'], optionalFields: ['voiceInput', 'budget'] },
    uiSurface: { route: '/concierge/advanced', componentName: 'AdvancedConciergeModule', appStoreExposure: 'hidden-behind-flag', consumerCopySafe: true },
    paymentFlow: 'none',
    complianceRisk: 'medium',
    score: { phiMarket: 6, phiExecution: 4, deltaDifferentiation: 7, feasibility: 5, lambdaSimilarity: 0.6 },
    constraints: { appStoreRisk: 4, engineeringEffort: 4, complianceRisk: 'medium', revenuePotential: 3, timeToReleaseWeeks: 4 },
    summary: 'Keep light/frozen until Parker release is stable; avoid expanding AI scope for current App Store review.',
    dependencies: ['search', 'voice-input', 'privacy-review'],
  }),
] as const satisfies readonly FeatureModule[];

export type FeatureModuleRegistryId = (typeof featureModules)[number]['id'];