import { defineFeatureModule, type FeatureModule } from './featureModule.ts';

export const swipeableCardModules = [
  defineFeatureModule({
    id: 'discover-swipe-deck',
    name: 'Discover Swipe Deck',
    stage: 'app-store-safe',
    audience: ['parker-consumer'],
    route: '/discover',
    featureFlag: 'VITE_FEATURE_DISCOVER_SWIPE_DECK',
    appleReviewSafe: true,
    dataContract: { schemaName: 'DiscoverCard', version: 1, requiredFields: ['id', 'type', 'name', 'image', 'distance'], optionalFields: ['entryType', 'ticketUrl', 'eventDate', 'features'] },
    uiSurface: { route: '/discover', componentName: 'SwipeableCard', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'stripe',
    complianceRisk: 'low',
    score: { phiMarket: 9, phiExecution: 8, deltaDifferentiation: 7, feasibility: 9, lambdaSimilarity: 0.95 },
    constraints: { appStoreRisk: 2, engineeringEffort: 2, complianceRisk: 'low', revenuePotential: 4, timeToReleaseWeeks: 1 },
    summary: 'Primary consumer swipe experience for venues, parking, and discovery cards.',
    dependencies: ['venues.list', 'google-places', 'saved-spots'],
  }),
  defineFeatureModule({
    id: 'home-events-carousel',
    name: "Home What's Happening Carousel",
    stage: 'app-store-safe',
    audience: ['parker-consumer', 'venue-partner'],
    route: '/',
    featureFlag: 'VITE_FEATURE_HOME_EVENTS_CAROUSEL',
    appleReviewSafe: true,
    dataContract: { schemaName: 'HomeEventCard', version: 1, requiredFields: ['id', 'title', 'venue', 'time', 'price'], optionalFields: ['ticketUrl', 'emoji', 'image'] },
    uiSurface: { route: '/', componentName: 'HomeEventsCarousel', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'stripe',
    complianceRisk: 'medium',
    score: { phiMarket: 8, phiExecution: 7, deltaDifferentiation: 6, feasibility: 8, lambdaSimilarity: 0.8 },
    constraints: { appStoreRisk: 3, engineeringEffort: 2, complianceRisk: 'medium', revenuePotential: 4, timeToReleaseWeeks: 2 },
    summary: 'Swipeable home row for tonight events and ticketable discovery.',
    dependencies: ['events-feed', 'checkout'],
  }),
  defineFeatureModule({
    id: 'home-live-crowd-carousel',
    name: 'Home Live Crowd Carousel',
    stage: 'app-store-safe',
    audience: ['parker-consumer'],
    route: '/',
    featureFlag: 'VITE_FEATURE_HOME_LIVE_CROWD_CAROUSEL',
    appleReviewSafe: true,
    dataContract: { schemaName: 'LiveCrowdVenueCard', version: 1, requiredFields: ['id', 'name', 'category', 'crowd'], optionalFields: ['entryType', 'entryPrice', 'parking'] },
    uiSurface: { route: '/', componentName: 'HomeLiveCrowdCarousel', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'none',
    complianceRisk: 'low',
    score: { phiMarket: 8, phiExecution: 8, deltaDifferentiation: 7, feasibility: 9, lambdaSimilarity: 0.9 },
    constraints: { appStoreRisk: 2, engineeringEffort: 2, complianceRisk: 'low', revenuePotential: 3, timeToReleaseWeeks: 1 },
    summary: 'Swipeable home row ranking current venue energy and wait context.',
    dependencies: ['venues.list', 'crowd-signal'],
  }),
  defineFeatureModule({
    id: 'home-trending-carousel',
    name: 'Home Trending Carousel',
    stage: 'app-store-safe',
    audience: ['parker-consumer'],
    route: '/',
    featureFlag: 'VITE_FEATURE_HOME_TRENDING_CAROUSEL',
    appleReviewSafe: true,
    dataContract: { schemaName: 'TrendingVenueCard', version: 1, requiredFields: ['id', 'name', 'category'], optionalFields: ['crowd', 'checkinCount'] },
    uiSurface: { route: '/', componentName: 'HomeTrendingCarousel', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'none',
    complianceRisk: 'low',
    score: { phiMarket: 7, phiExecution: 8, deltaDifferentiation: 6, feasibility: 9, lambdaSimilarity: 0.9 },
    constraints: { appStoreRisk: 2, engineeringEffort: 2, complianceRisk: 'low', revenuePotential: 3, timeToReleaseWeeks: 1 },
    summary: 'Swipeable home row for trending venues from check-ins or live crowd fallback.',
    dependencies: ['venues.list', 'social-checkins'],
  }),
  defineFeatureModule({
    id: 'home-social-carousel',
    name: 'Home Social Carousel',
    stage: 'app-store-safe',
    audience: ['parker-consumer'],
    route: '/',
    featureFlag: 'VITE_FEATURE_HOME_SOCIAL_CAROUSEL',
    appleReviewSafe: true,
    dataContract: { schemaName: 'SocialVenueCard', version: 1, requiredFields: ['id', 'userName', 'venueName', 'timestamp'], optionalFields: ['crowdLabel'] },
    uiSurface: { route: '/', componentName: 'HomeSocialCarousel', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'none',
    complianceRisk: 'medium',
    score: { phiMarket: 6, phiExecution: 7, deltaDifferentiation: 7, feasibility: 7, lambdaSimilarity: 0.75 },
    constraints: { appStoreRisk: 3, engineeringEffort: 3, complianceRisk: 'medium', revenuePotential: 3, timeToReleaseWeeks: 2 },
    summary: 'Swipeable friend-presence row; must remain privacy-safe and opt-in.',
    dependencies: ['social-feed', 'privacy-review'],
  }),
  defineFeatureModule({
    id: 'home-category-strip',
    name: 'Home Category Strip',
    stage: 'app-store-safe',
    audience: ['parker-consumer'],
    route: '/',
    featureFlag: 'VITE_FEATURE_HOME_CATEGORY_STRIP',
    appleReviewSafe: true,
    dataContract: { schemaName: 'CategoryPillCard', version: 1, requiredFields: ['label', 'category', 'priority', 'reason'], optionalFields: ['personalized'] },
    uiSurface: { route: '/', componentName: 'HomeCategoryStrip', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'none',
    complianceRisk: 'low',
    score: { phiMarket: 7, phiExecution: 9, deltaDifferentiation: 5, feasibility: 9, lambdaSimilarity: 0.95 },
    constraints: { appStoreRisk: 1, engineeringEffort: 1, complianceRisk: 'low', revenuePotential: 2, timeToReleaseWeeks: 1 },
    summary: 'Swipeable category chips that route members into filtered discovery.',
    dependencies: ['preferences', 'search'],
  }),
  defineFeatureModule({
    id: 'home-nearby-carousel',
    name: 'Home Nearby Carousel',
    stage: 'app-store-safe',
    audience: ['parker-consumer'],
    route: '/',
    featureFlag: 'VITE_FEATURE_HOME_NEARBY_CAROUSEL',
    appleReviewSafe: true,
    dataContract: { schemaName: 'NearbyLocationCard', version: 1, requiredFields: ['name', 'distance', 'spots', 'available'], optionalFields: ['crowd', 'priority'] },
    uiSurface: { route: '/', componentName: 'HomeNearbyCarousel', appStoreExposure: 'current-app-store', consumerCopySafe: true },
    paymentFlow: 'none',
    complianceRisk: 'low',
    score: { phiMarket: 8, phiExecution: 8, deltaDifferentiation: 6, feasibility: 9, lambdaSimilarity: 0.9 },
    constraints: { appStoreRisk: 2, engineeringEffort: 2, complianceRisk: 'low', revenuePotential: 3, timeToReleaseWeeks: 1 },
    summary: 'Swipeable nearby parking and venue row for immediate member utility.',
    dependencies: ['venues.list', 'parking-availability'],
  }),
] as const satisfies readonly FeatureModule[];

export type SwipeableCardModuleId = (typeof swipeableCardModules)[number]['id'];