/**
 * Disclaimer — accuracy disclaimer for crowd data, parking prices, AI recommendations.
 * Accessible at /disclaimer (no auth required).
 * Last updated: 2026-04-13
 */
export function Disclaimer() {
  return (
    <div className="min-h-screen bg-black text-white/90 px-6 py-12 max-w-2xl mx-auto leading-relaxed">
      <h1 className="text-3xl font-bold mb-2">Disclaimer</h1>
      <p className="text-white/50 text-sm mb-8">Last updated: April 13, 2026</p>

      <p className="mb-6">
        Bytspot ("App") provides real-time crowd data, parking information, venue details, and
        AI-powered recommendations for informational purposes only. By using the App, you
        acknowledge and agree to the following disclaimers.
      </p>

      <Section title="1. Accuracy of Data">
        <p className="mb-3">
          Crowd levels, wait times, and venue capacity indicators displayed in the App are
          <strong> estimates</strong> based on aggregated data sources including user reports,
          sensor data, and algorithmic modeling. These figures may not reflect actual real-time
          conditions. Bytspot does not guarantee the accuracy, completeness, or timeliness of
          any crowd data shown.
        </p>
      </Section>

      <Section title="2. Parking Information">
        <p className="mb-3">
          Parking availability, pricing, and location information displayed in the App are
          sourced from third-party providers and public data. Actual parking availability and
          pricing may differ from what is shown. Bytspot is not responsible for parking
          violations, towing, incorrect pricing, or unavailable spaces. Always verify parking
          rules and signage at the physical location.
        </p>
      </Section>

      <Section title="3. AI Recommendations">
        <p className="mb-3">
          The AI Concierge and automated recommendations provided by the App are generated by
          machine learning models and may contain errors, outdated information, or suggestions
          that do not match your preferences or needs. AI-generated content should not be relied
          upon as the sole basis for any decision, including but not limited to transportation,
          dining, or safety decisions.
        </p>
      </Section>

      <Section title="4. Venue Information">
        <p className="mb-3">
          Venue hours, menus, ratings, photos, and other details are sourced from third-party
          APIs and user contributions. Bytspot does not independently verify this information.
          Venues may change their hours, close temporarily, or differ from the information shown.
          Always confirm details directly with the venue before visiting.
        </p>
      </Section>

      <Section title="5. Location Services">
        <p className="mb-3">
          The App uses your device's location to provide relevant nearby results. GPS accuracy
          depends on your device, environment, and signal conditions. Bytspot is not responsible
          for inaccurate location data or navigation decisions made based on the App's
          location-based features.
        </p>
      </Section>

      <Section title="6. No Professional Advice">
        <p className="mb-3">
          Nothing in the App constitutes professional advice (legal, financial, safety, or
          otherwise). The App is a convenience tool for discovering venues, checking crowd
          conditions, and finding parking. Users should exercise their own judgment and due
          diligence.
        </p>
      </Section>

      <Section title="7. Limitation of Liability">
        <p className="mb-3">
          To the maximum extent permitted by applicable law, Bytspot and its officers, directors,
          employees, and agents shall not be liable for any direct, indirect, incidental, special,
          consequential, or punitive damages arising out of or relating to your use of the App,
          including but not limited to reliance on crowd data, parking information, AI
          recommendations, or venue details.
        </p>
      </Section>

      <Section title="8. Changes to This Disclaimer">
        <p className="mb-3">
          We may update this Disclaimer from time to time. Continued use of the App after changes
          constitutes acceptance of the revised Disclaimer.
        </p>
      </Section>

      <div className="mt-12 pt-6 border-t border-white/10 text-white/40 text-xs">
        <p>© {new Date().getFullYear()} Bytspot. All rights reserved.</p>
        <p className="mt-1">Questions? Contact us at bytspotapp@gmail.com</p>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-semibold text-cyan-400 mb-3">{title}</h2>
      <div className="text-white/70 text-[15px]">{children}</div>
    </section>
  );
}
